"""rename_metadata_to_meta_info_in_prediction

Revision ID: 018d6436b6f8
Revises: ae666d42ee9a
Create Date: 2025-06-16 21:54:10.554557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018d6436b6f8'
down_revision: Union[str, None] = 'ae666d42ee9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('meta_info', sa.Text(), nullable=True))
    op.drop_index('ix_prediction_product_user_timeframe', table_name='prediction')
    op.drop_index('ix_prediction_user_created', table_name='prediction')
    op.drop_index('ix_prediction_user_sid', table_name='prediction')
    op.drop_constraint('uq_prediction_user_product_period', 'prediction', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_prediction_user_product_period', 'prediction', ['user_sid', 'product_sid', 'timeframe', 'period_start', 'period_end'])
    op.create_index('ix_prediction_user_sid', 'prediction', ['user_sid'], unique=False)
    op.create_index('ix_prediction_user_created', 'prediction', ['user_sid', 'created_at'], unique=False)
    op.create_index('ix_prediction_product_user_timeframe', 'prediction', ['product_sid', 'user_sid', 'timeframe', 'period_start'], unique=False)
    op.drop_column('prediction', 'meta_info')
    # ### end Alembic commands ###
