"""Add storage duration type

Revision ID: 37cf20593582
Revises: f8f729bfedef
Create Date: 2025-04-28 12:20:44.378635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37cf20593582'
down_revision: Union[str, None] = 'f8f729bfedef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('storage_duration_type', sa.Enum('DAY', 'MONTH', 'YEAR', name='storagedurationtype'), nullable=True))
    op.alter_column('product', 'currency',
               existing_type=postgresql.ENUM('KZT', 'USD', 'EUR', 'RUB', name='currency'),
               server_default=None,
               nullable=True)
    op.alter_column('product', 'storage_duration',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'storage_duration',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               nullable=False)
    op.alter_column('product', 'currency',
               existing_type=postgresql.ENUM('KZT', 'USD', 'EUR', 'RUB', name='currency'),
               server_default=sa.text("'KZT'::currency"),
               nullable=False)
    op.drop_column('product', 'storage_duration_type')
    # ### end Alembic commands ###
