"""Add storage duration type

Revision ID: c912b5318def
Revises: f8f729bfedef
Create Date: 2025-04-28 12:38:17.137111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c912b5318def'
down_revision: Union[str, None] = 'f8f729bfedef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала создаем ENUM тип
    storage_duration_type = sa.Enum('DAY', 'MONTH', 'YEAR', name='storagedurationtype')
    storage_duration_type.create(op.get_bind(), checkfirst=True)

    # Теперь добавляем колонку, используя созданный тип ENUM
    op.add_column('product', sa.Column('storage_duration_type', storage_duration_type, nullable=True))

    op.alter_column('product', 'currency',
               existing_type=postgresql.ENUM('KZT', 'USD', 'EUR', 'RUB', name='currency'),
               server_default=None,
               nullable=True)
    op.alter_column('product', 'storage_duration',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'storage_duration',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               nullable=False)
    op.alter_column('product', 'currency',
               existing_type=postgresql.ENUM('KZT', 'USD', 'EUR', 'RUB', name='currency'),
               server_default=sa.text("'KZT'::currency"),
               nullable=False)
    op.drop_column('product', 'storage_duration_type')

    # Удаляем ENUM тип после удаления колонки
    sa.Enum(name='storagedurationtype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###