"""fix cart items table

Revision ID: e332d21eb82d
Revises: a165ec7f3cd3
Create Date: 2025-05-24 21:50:21.456965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e332d21eb82d'
down_revision: Union[str, None] = 'a165ec7f3cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cartitem', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index('ix_cartitem_store_item_sid', table_name='cartitem')
    op.drop_index('ix_cartitem_user_sid', table_name='cartitem')
    op.alter_column('warehouseitem', 'urgency_level',
               existing_type=postgresql.ENUM('NORMAL', 'URGENT', 'CRITICAL', name='urgencylevel'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouseitem', 'urgency_level',
               existing_type=postgresql.ENUM('NORMAL', 'URGENT', 'CRITICAL', name='urgencylevel'),
               nullable=False)
    op.create_index('ix_cartitem_user_sid', 'cartitem', ['user_sid'], unique=False)
    op.create_index('ix_cartitem_store_item_sid', 'cartitem', ['store_item_sid'], unique=False)
    op.alter_column('cartitem', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    # ### end Alembic commands ###
